### ISSUE TITLE
Compatible with cra3? 

### ISSUE THREAD

**Issue by jannikbuschke** [arackaf/customize-cra#106]
The readme only states CRA 2...
Is customize-cra usable with CRA 3?

**Comment by with-heart** [comment]
Hi @jannikbuschke, since `customize-cra` simply hooks into `react-app-rewired`'s `config-overrides` file, we support whatever version they support. 

I'm pretty sure `react-app-rewired` fully supports cra3, but I'll double-check that and update the `README` if so (#109). I'm also going to add `react-app-rewired` as a peer dependency, so warnings will be generated if an incompatible version is being used (#108).

Hope that helps!

**Comment by jannikbuschke** [comment]
yes, I also can confirm now that CRA 3 is supported.

**Comment by with-heart** [comment]
@jannikbuschke Awesome! Thank you!
