### ISSUE TITLE
babelInclude on a symlink folder does not work

### ISSUE THREAD

**Issue by royair** [arackaf/customize-cra#107]
i have an external component folder linked to my web project through npm-link.
on my web project i have configured config-override to babel parse the npm-linked folder withe the proper plugin.

this works well when not using npm link and simply downloading from npm
when using npm-link i get errors related to not using "babel/plugin-proposal-class-properties"

tried also replacing: 

> path.resolve('node_modules/@blio'),

with 

> fs.realpathSync('node_modules/@blio')

and it didn't help either

i am using:
"react-scripts": "3.0.0",
"customize-cra": "^0.2.14",

```
const { override, fixBabelImports, addBabelPlugin, babelInclude, addLessLoader } = require('customize-cra');
const path                                                                       = require('path');

module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true,
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { '@primary-color': '#047fff' },
  }),
  addBabelPlugin('@babel/plugin-proposal-class-properties'),
  babelInclude([
    path.resolve('src'), // don't forget this
    path.resolve('node_modules/@blio'),
  ]),
);
```

**Comment by with-heart** [comment]
Since `babelInclude` simply injects the provided array into `babel-loader` configuration, any issues with how `babel-loader` uses that configuration are outside the scope of the `customize-cra` project. Since this works fine when not using `link`, it means the issue stems from `babel-loader` and not `customize-cra`.

It appears that symlinks with `babel-loader` are a common issue that people face. I was able to find an issue that may be relevant to your issue: https://github.com/babel/babel-loader/issues/149

Unfortunately I don't know enough about `babel-loader` to assist beyond pointing you in that direction. Hope that helps!

**Comment by royair** [comment]
Thanks Mark,
I've found a workaround: using fs.realPathSync instead of Path.resolve

**Comment by with-heart** [comment]
Perfect! That's good to know. Thanks @royair

**Comment by switz** [comment]
> Thanks Mark,
> I've found a workaround: using fs.realPathSync instead of Path.resolve

Life saver! Only one note for future visitors, it's `fs.realpathSync` (see casing).

Thanks so much @royair

**Comment by royair** [comment]
fs.realpathSync indeed!
Thanks
