### ISSUE TITLE
addLessLoader Failed to compile

### ISSUE THREAD

**Issue by Menci** [arackaf/customize-cra#199]
```
Failed to compile.

./src/layouts/AppLayout.module.less (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-8-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-8-3!./src/layouts/AppLayout.module.less)
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }
```

Maybe same as https://github.com/rails/webpacker/issues/2197?

**Comment by with-heart** [comment]
Hi @Menci, sorry for not getting back to you sooner. I appreciate the issue and your PR.

We currently have #185 by @onlyling merged into the `next` branch (since it's a breaking change). It uses the new `modules` configuration format for `css-loader`.

However that PR changed `localIdentName` from `"[path][name]__[local]--[hash:base64:5]"` to `"[local]--[hash:base64:5]"`, while your change preserves the existing `localIdentName`.

Do you have any familiarity with `css-loader`/`less-loader` configuration? I don't know much about either of them, so I'm not sure what would work better for us. Any opinions?

**Comment by with-heart** [comment]
Closing this in favor of #201 so we can continue all `addLessLoader`-related conversation in one place. Please join us there :)
