### ISSUE TITLE
localIdent cause an error during build with css-modules

### ISSUE THREAD

**Issue by Driky** [arackaf/customize-cra#221]
https://github.com/arackaf/customize-cra/blob/404854bcbe7436f5834e4c4863001610951d5c3c/src/customizers/webpack.js#L177-L197

I followed this article to setup a create react app project with `less loader` and `css modules`. And once you try to actually import a less file, for exemple:
```
import styles from "./App.module.less";
```

it causes the following error during build (with yarn start):
```

s-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-8-3!./src/App.module.less
)
ValidationError: Invalid options object. CSS Loader has been initialized using an options object tha
t does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esM
odule? }
```

is there a way to override the settings causing this without actually changing the lib ?

Edit: I tested removing `localIdentName` and it works. Although I'm sure it's there for some reason.

**Comment by bighansen** [comment]
I've met the same error. 
I create a project with create-react-app2.x, react-app-rewired.
In this way I want to use less-loader to import x.module.less file with the follow config:

`
const { override, fixBabelImports, addLessLoader } = require('customize-cra');

module.exports = override(
    fixBabelImports('import', {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
    }),
    addLessLoader({
        javascriptEnabled: true,
        modifyVars: { 
            '@primary-color': '#0168B3'
        },
        localIdentName: '[local]--[hash:base64:5]',
    }),
);
`

**Comment by iamsmartloser** [comment]
me too

**Comment by drixta** [comment]
Same issue here

**Comment by damikun** [comment]
Same did anybody find some workaround ??

**Comment by Driky** [comment]
was this project abandoned ?

**Comment by Anish-Agnihotri** [comment]
Hi @Driky,

I've just received repo moderator and NPM publishing access from Adam for this repository, and will be working to catch-up on the all the open issues and PRs this week.

`localIdentName` seems to be a common issue faced across the various threads, so that is the highest priority fix for the time-being. There seem to be a few PR's implementing related fixes, so I'll be reviewing those, merging them in, and releasing a new package version near mid-day tomorrow.

Will keep you in the loop.

**Comment by Driky** [comment]
Thank you Anish ! Very much appreciated. If you need someone to test something give me a ping ;-)

**Comment by Anish-Agnihotri** [comment]
Hi @Driky,

Can you do me a quick favour and test your `less loader`/`css modules` configuration using the `customize-cra@next` package. You'll have to slightly modify the `localIdentName` so that it's:

```
getLessLoader({
	//...
	cssOptions: {
		localIdentName: "your_localidentname_here"
	}
})
```

Essentially:
1. Remove your current `customize-cra`.
2. Add `customize-cra@next`.
3. Slightly modify your current config settings to nest `localIdentName` under `cssOptions`.

Let me know if this works and I'll prepare to merge it into master.

**Comment by Driky** [comment]
Alright I will test that tomorrow (actually later today, it's 3am here).

**Comment by Driky** [comment]
Ok so I tried to test. First just by removing the old `customize-car` and re-installing with `@next` allowed my project to compile, when it would have been crashing before.

But I have a small problem/question: the other modification that you are asking me to make, I'm not sure where in my `config-overrides.js` I should put it. I never used `getLessLoader`. Here is my current file: 
```javascript
/* eslint-disable no-undef */
/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-var-requires */

const { override, fixBabelImports, addLessLoader } = require('customize-cra');

module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true,
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: {
      '@primary-color': '#f48549', // customize as needed
      '@link-color': '#e6a07c', // customize as needed
      '@font-size-base': '18px', // customize as needed
    },
  })
);

```

**Comment by Anish-Agnihotri** [comment]
Hi @Driky,

No worries—sorry, ignore the second part with `addLessLoader`.

As long as reinstalling with `@next` allows your project to compile and work as normal, I am good to go, and will work on getting this update pushed upstream into master within the next day (so that you don't have to use `@next`).

**Comment by Anish-Agnihotri** [comment]
Hi @Driky,

The changes have now been pushed upstream to master, and you can reinstall `customize-cra` without the `@next` version. Let me know if you run into any issues—else, I'll close this issue out in a few days time.

**Comment by Driky** [comment]
@Anish-Agnihotri if it's alright with you I will close the issue ?
