### ISSUE TITLE
Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by francisleigh** [arackaf/customize-cra#279]
I am using react-app-rewired to configure my CRA project as I was having issues with 2 co-existing versions of React which I'm sure is a very common use-case for `react-app-rewired/customize-cra`.

Everything has been fine until I required installing `react-native-calendars` as a dependency. 
As you can see in my `addBabelPlugins` config; I have needed to install `@babel/plugin-proposal-class-properties` to transpile the libraries' components... I am now however getting an error that complains about JSX in my codebase which I thought would already be handled by CRA in the first place and seeing as we are overwriting/extending CRA with `react-app-rewired` i didn't think I would need to add additional plugins/presets such as `@babel/preset-react` & `@babel/plugin-syntax-jsx`... 

can somebody point me in the right direction? I'm hoping this issue is common and I have just searched the issues page poorly.

Thank you

### Info
```ruby
react@17.0.1
react-scripts@3.4.3
customize-cra@1.0.0 
npm@6.14.9
node@14.8.0
```

### Error
```ruby
Failed to compile.

./src/App.js
SyntaxError: /Users/.../src/App.js: Support for the experimental syntax 'jsx' isn't currently enabled (28:5):

  26 | 
  27 |   return (
> 28 |     <Router>
     |     ^
  29 |       <Switch>

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
```

### config-overrides.js
```javascript
const {
  override,
  addWebpackAlias,
  babelInclude,
  addBabelPresets,
  addBabelPlugins,
} = require('customize-cra');

module.exports = override(
  babelInclude([
    require.resolve('./src'),
    require.resolve('./node_modules/react-native-calendars'),
  ]),
  ...addBabelPresets(
    '@babel/preset-react',
  ),
  ...addBabelPlugins(
    '@babel/plugin-proposal-class-properties', // <~ needed for react-native-calendars
    '@babel/plugin-syntax-jsx',
  ),
  addWebpackAlias({
    react: require.resolve('./node_modules/react'),
  }),
);
```

**Comment by dawnmist** [comment]
Try renaming the file "App.jsx" - I know that for typescript there are different language options for `ts` vs `tsx` files, with JSX only being supported in the tsx files.

Edit: Actually, that may be a red herring. Does Babel Include normally let you include multiple babel files, or is the second one in your list supposed to be actually referenced from _inside_ your normal babel include file? It may be clobbering/completely replacing your own file rather than adding to it.

**Comment by francisleigh** [comment]
@dawnmist Thank you for your reply. 

From the [*docs*](https://github.com/arackaf/customize-cra/blob/master/api.md#babelinclude)
### babelInclude
Overwrites the `include` option for babel loader, for when you need to transpile a module in your `node_modules` folder.

So it looks like it's clobbering it... do you know of a method that merges the two?

**Comment by francisleigh** [comment]
@dawnmist I must say that changing `App.js` to `.jsx` did allow the error to trickle through to the next `.js` Component and error there. so that is definitely a way to avoid the error. That said. i'd rather not declare my components as `.jsx`

**Comment by francisleigh** [comment]
I fear there's something wrong here. i'm following the docs as best I can and it's not playing nicely. my App is pretty straight forward in terms of folder structure etc...

**Comment by dawnmist** [comment]
Sorry to take a while to reply - I'm in Australia, so difficult timezone and I'd needed to look into things further.

A few questions:
1. react-native-calendars is a react-native (mobile app) component, not a standard react (web app) component. Are you working on a react project or a react-native project?
2. Why does the `./node_modules/react-native-calendars` need to be included? It's not listed on their readme as something needed to be able to use the react-native-calendars?

I am thinking that including the babel config from react-native-calendars is likely unnecessary, and further is actually causing issues due to the differences between react and react-native. It is also not a common use-case to have multiple versions of react in the same project (or subproject if using a monorepo), which is likely to cause a lot of issues.

Can you explain a bit more about what it is that you are trying to do? Is this actually a react-native project?

**Comment by francisleigh** [comment]
That's not a problem i saw that you're in Melbourne so assumed you'd take a while to reply. :-) 

So I have two projects. A React-Native project and a CRA Project. 
With the CRA Project we are using react-native-web so all the React-Native components are rendered as DOM elements... 
From what I can see on the react-native-calendars library is that it **is** compatible with `react-native-web` e.g it doesn't use any IOS or Android specific components, just React-Native components.

This said, it **does** use `class-properties` which I need `@babel/plugin-proposal-class-properties` for as the CRA w/ `customize-cra` App doesn't seem to handle out-of-the-box...

I needed to `babelInclude` `./node_modules/react-native-calendars`  so that I could tell the component to be transpiled with the `@babel/plugin-proposal-class-properties` plugin.

**Comment by dawnmist** [comment]
Ok, that makes more sense now - and confirms that you're doing stuff I don't have any experience in. :)

One thing I can suggest after having been poking around in the Babel docs [here](https://babeljs.io/docs/en/plugins#plugin-ordering), is the plugin order _might_ be backwards. It's failing at the JSX parts, and the plugins run in their defined order - so it _might_ be that the proposal-class-properties plugin doesn't know what to do with code containing JSX. However, it's not something I can test here so I don't know if it'll cause issues in applying the class properties. Other than that, I'd have to hand off at this point to someone who has a better knowledge of babel.

**Comment by francisleigh** [comment]
@dawnmist Really appreciate your help. i dug further into react-native-calendar's lib and found [This answer](https://github.com/wix/react-native-calendars/issues/521#issuecomment-692653369) Which seems to be working for me... 

Again I appreciate your help :-)
